name: iOS SDK Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
      
      - name: Resolve Dependencies
        run: |
          xcodebuild -resolvePackageDependencies

      - name: Run All Tests with Coverage
        run: |
          chmod +x ./Tests/run-tests.sh
          ./Tests/run-tests.sh

      - name: Find Coverage Data
        run: |
          COVERAGE_DIR=$(find ~/Library/Developer/Xcode/DerivedData -name "*.xcresult" | tail -1)
          echo "COVERAGE_DIR=$COVERAGE_DIR" >> $GITHUB_ENV

      - name: Convert Coverage Data to LCOV
        run: |
          if [ -z "$COVERAGE_DIR" ]; then
            echo "Coverage data not found!"
            exit 1
          fi
          
          xcrun xccov view --report --json $COVERAGE_DIR > coverage.json
          echo "Coverage report generated."

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.json
